def projectName = "TestFront"
def dockerImageName = "web-axity-holamundo-angular"
def dockerContainerName = "firtsAppDocker"
def NEXUS_DOCKER_REPO = "localhost:8085"

pipeline {
    agent any
    stages{

        stage('Checkout Project Test'){
            steps{
                checkout([$class: 'GitSCM',
                        branches: [[name: "${branch}"]],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [],
                        gitTool: 'Default',
                        submoduleCfg: [],
                        userRemoteConfigs: [[credentialsId: 'Git-SSH-Credentials', url: "git@github.com:Axity-DieGom/Test-Front.git"]]
                ])
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script{
                    def scannerHome = tool 'sonarqube';
                        withSonarQubeEnv("sonarqube"){
                            sh "${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=${projectName} \
                            -Dsonar.projectName=${projectName}"
                        }
                }
            }
        }
        stage('Docker Build'){
            steps{
                script{
                    sh "pwd"
                    sh "docker build -t ${dockerImageName} ."
                }
            }
        }
        /*stage('Docker run'){
            steps{
                script{
                    sh "docker container run --name ${dockerContainerName} -dp 83:80 ${dockerImageName}"
                }
            }
        }*/
        stage('Aws login'){
            steps{
                script{
                    sh "aws ecr get-login-password --profile dev --region us-east-1 | docker login --username AWS --password-stdin 152125693760.dkr.ecr.us-east-1.amazonaws.com"
                }
            }
        }
        stage('Docker Tag'){
            steps{
                script{
                    sh "docker tag ${dockerImageName}:latest 152125693760.dkr.ecr.us-east-1.amazonaws.com/docker-devops:latest"
                }
            }
        }
        stage('Docker push'){
            steps{
                script{
                    sh "docker push 152125693760.dkr.ecr.us-east-1.amazonaws.com/docker-devops:latest"
                }
            }
        }
    }
}