def projectName = "TestFront"

pipeline {
    agent any
    stages{

        stage('Checkout Project Test'){
            steps{
                checkout([$class: 'GitSCM',
                        branches: [[name: "main"]],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [],
                        gitTool: 'Default',
                        submoduleCfg: [],
                        userRemoteConfigs: [[credentialsId: 'Git-SSH-Credentials', url: "git@github.com:Axity-DieGom/Test-Front.git"]]
                ])
            }
        }
        stage('SonarQube Analysis') {
            steps {
                script{
                    def scannerHome = tool 'sonarqube';
                        withSonarQubeEnv("sonarqube"){
                            sh "${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=${projectName} \
                            -Dsonar.projectName=${projectName}"
                        }
                }
            }
        }
    }
}